<?php
# This file was automatically generated by the MediaWiki 1.28.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

/* global $wgUser;
if(!$wgUser->isAllowed('edit')) {
    <style type="text/css">
        #ca-viewsource { display: none !important; }
    </style>
} */

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "QubeWire Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://192.168.113.35";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/qw-logo.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@localhost";
$wgPasswordSender = "apache@localhost";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost:3307";
$wgDBname = "qw_wiki";
$wgDBuser = "root";
$wgDBpassword = "r00t@1234";

# MySQL specific settings
$wgDBprefix = "qw";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# List of file extensions allowed to be uploaded
$wgFileExtensions = [ 'png', 'gif', 'jpg', 'jpeg', 'webp', 'txt', 'doc',
 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'mpp', 'tiff', 'pdf', 'odt', 'ods',
 'odp', 'odg' ];

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "01303bf2a5bd5a9d15589f2224bd3d5c26972aa5dd17e14cb663d6b0f327863e";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "d25ab29214c7fdb9";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

unset($wgGroupPermissions['bot']);
unset($wgGroupPermissions['bureaucrat']);
unset($wgGroupPermissions['autoconfirmed']);

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['read'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['createpage'] = false;
$wgGroupPermissions['*']['createtalk'] = false;
$wgGroupPermissions['*']['writeapi'] = false;
$wgGroupPermissions['*']['editmyusercss'] = false;
$wgGroupPermissions['*']['editmyuserjs'] = false;
$wgGroupPermissions['*']['viewmywatchlist'] = false;
$wgGroupPermissions['*']['editmywatchlist'] = false;
$wgGroupPermissions['*']['viewmyprivateinfo'] = false;
$wgGroupPermissions['*']['editmyprivateinfo'] = false;
$wgGroupPermissions['*']['editmyoptions'] = false;
$wgGroupPermissions['*']['patrolmarks'] = false;

$wgGroupPermissions['user']['createaccount'] = false;
$wgGroupPermissions['user']['edit'] = false;
$wgGroupPermissions['user']['move'] = false;
$wgGroupPermissions['user']['move-subpages'] = false;
$wgGroupPermissions['user']['move-rootuserpages'] = false; // can move root userpages
$wgGroupPermissions['user']['move-categorypages'] = false;
$wgGroupPermissions['user']['movefile'] = false;
$wgGroupPermissions['user']['read'] = true;
$wgGroupPermissions['user']['createpage'] = false;
$wgGroupPermissions['user']['createtalk'] = false;
$wgGroupPermissions['user']['writeapi'] = false;
$wgGroupPermissions['user']['upload'] = false;
$wgGroupPermissions['user']['reupload'] = false;
$wgGroupPermissions['user']['reupload-shared'] = false;
$wgGroupPermissions['user']['minoredit'] = false;
$wgGroupPermissions['user']['purge'] = false;
$wgGroupPermissions['user']['sendemail'] = false;
$wgGroupPermissions['user']['applychangetags'] = false;
$wgGroupPermissions['user']['changetags'] = false;
$wgGroupPermissions['user']['editcontentmodel'] = false;

$wgGroupPermissions['Users']['createaccount'] = false;
$wgGroupPermissions['Users']['edit'] = false;
$wgGroupPermissions['Users']['move'] = false;
$wgGroupPermissions['Users']['move-subpages'] = false;
$wgGroupPermissions['Users']['move-rootuserpages'] = false; // can move root userpages
$wgGroupPermissions['Users']['move-categorypages'] = false;
$wgGroupPermissions['Users']['movefile'] = false;
$wgGroupPermissions['Users']['read'] = true;
$wgGroupPermissions['Users']['createpage'] = false;
$wgGroupPermissions['Users']['createtalk'] = false;
$wgGroupPermissions['Users']['writeapi'] = false;
$wgGroupPermissions['Users']['upload'] = false;
$wgGroupPermissions['Users']['reupload'] = false;
$wgGroupPermissions['Users']['reupload-shared'] = false;
$wgGroupPermissions['Users']['minoredit'] = false;
$wgGroupPermissions['Users']['purge'] = false;
$wgGroupPermissions['Users']['sendemail'] = false;
$wgGroupPermissions['Users']['applychangetags'] = false;
$wgGroupPermissions['Users']['changetags'] = false;
$wgGroupPermissions['Users']['editcontentmodel'] = false;

$wgGroupPermissions['sysop']['edit'] = true;
$wgGroupPermissions['sysop']['userrights'] = true;
$wgGroupPermissions['sysop']['noratelimit'] = true;
$wgGroupPermissions['sysop']['autoconfirmed'] = true;
$wgGroupPermissions['sysop']['editsemiprotected'] = true;
$wgGroupPermissions['sysop']['createpage'] = true;
$wgGroupPermissions['sysop']['createtalk'] = true;
$wgGroupPermissions['sysop']['upload'] = true;
$wgGroupPermissions['sysop']['reupload'] = true;
$wgGroupPermissions['sysop']['reupload-shared'] = true;

/* $wgGroupPermissions['bot']['bot'] = false;
$wgGroupPermissions['bot']['autoconfirmed'] = false;
$wgGroupPermissions['bot']['editsemiprotected'] = false;
$wgGroupPermissions['bot']['nominornewtalk'] = false;
$wgGroupPermissions['bot']['autopatrol'] = false;
$wgGroupPermissions['bot']['suppressredirect'] = false;
$wgGroupPermissions['bot']['apihighlimits'] = false;
$wgGroupPermissions['bot']['writeapi'] = false;
 */
## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'CologneBlue' );
wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'WikiEditor' );


# End of automatically generated settings.
# Add more configuration options below.

require_once "$IP/extensions/WYSIWYG/WYSIWYG.php";
$wgGroupPermissions['*']['wysiwyg'] = true;
require_once "$IP/extensions/SlimboxThumbs/SlimboxThumbs.php";
$wgGroupPermissions['*']['slimboxthumbs'] = true;